### ISSUE TITLE
Easy menu like choice support for different builds/ platforms

### ISSUE THREAD

**Issue by mwargers** [askeing/taskcluster-util-python#14]
@jlorenzo just pointed me out how to download mozilla-central nightly build for Aries:
taskcluster_download --credential credential.json -n gecko.v1.mozilla-central.latest.linux.aries-eng.opt -a private/build/aries.zip

That's nice of him, but it would be even nicer if taskcluster_download gave me a menu like choice of what I want to download and for which platform, just like we currently have for flash_pvt.py.

**Comment by mwargers** [comment]
It would also be nice if the tool would explain what the tc_credentials.json file consists of and how to get these credentials.

**Comment by askeing** [comment]
I'm still trying to implement to `taskcluster_traverse` as a GUI tool for downloading artifacts.
Maybe next week we will have a prototype.
Hopefully it will fit your need :)

**Comment by mshal** [comment]
Can you try to use the gecko.v2 indexes? The latest aries eng build from your example would be: gecko.v2.mozilla-central.latest.b2g.aries-eng-opt

The v2 indexes are the same whether the builds were generated by Taskcluster or buildbot, so it should be a bit easier to browse around.

I'm also curious how to setup tc_credentials.json, since it sounds like the temporary credentials given by auth.taskcluster.net aren't supposed to work :). I'd love to get this incorporated into mozregression for b2g device bisecting!

**Comment by askeing** [comment]
@mshal 
After trying the gecko.v2, I can download artifacts from it by version 0.0.16.
ex: download `sources.xml` and `live.log` files.

``` bash
$ taskcluster_traverse -n gecko.v2.mozilla-central.latest.b2g.aries-eng-opt
WARNING: No certificate is present in the given credentials. If the credentials are temporary you won't be able to download anything
INFO: Starting new HTTPS connection (1): index.taskcluster.net
INFO: Starting new HTTPS connection (1): index.taskcluster.net
INFO: Starting new HTTPS connection (1): queue.taskcluster.net
INFO: Download: private/build/sources.xml
Progress: | 100%, 18054 of 18054, Time: 0:00:00  88.86 kB/s                                                           
INFO: Download: public/logs/live.log
Progress: | 100%, 2422923 of 2422923, Time: 0:00:01   1.22 MB/s
```

And as far as I know, the Taskcluster Python client doesn't support  temporary credentials right now, so Taipei QA team use the special credentials which is created from Bug 1179080 for downloading.

**Comment by askeing** [comment]
Hi @mwargers ,
The `taskcluster_traverse`, which provide the GUI dialog, is ready.
I think it will make download easier than before :)

**Comment by askeing** [comment]
@mwargers, please feel free to reopen it if there are any concern.
