### ISSUE TITLE
list the artifacts of a task

### ISSUE THREAD

**Issue by parkouss** [askeing/taskcluster-util-python#2]
It would be awesome to be able to list the artifacts of a task, given a namespace/taskid.

**Comment by askeing** [comment]
The following two commands can list the latest artifacts:
`taskcluster_download -n <NAMESPACE>`
`taskcluster_download -t <TASKID>`

Please feel free to tell me if it doesn't work :)

**Comment by askeing** [comment]
it seems like we can close this issue.
please re-open it if it doesn't work.

**Comment by parkouss** [comment]
Sorry I did not have the time to look at that yet - thanks for looking at it!
Well I tried:

```
taskcluster_download -n buildbot.revisions.1c5b4332e2f1.mozilla-inbound.linux64
### /home/jp/dev/mozregression/tc_credentials.json is not a file or is not exist.
```

So this is something else, because this namespace does not require credentials. Maybe I should open another issue for this ? (ie not requiring a credential files)
