### ISSUE TITLE
Make the destination folder optional

### ISSUE THREAD

**Issue by JohanLorenzo** [askeing/taskcluster-util-python#4]
If a destination folder is not provided, then we could use the current folder (like wget).

**Comment by askeing** [comment]
Hmm, that sounds reasonable.

By the way, do we have to keep the folder structure of artifact?
For example,
downloading the `private/build/sources.xml`
1. put into local `<CUR_DIR>/private/build/sources.xml`
2. put into local `<CUR_DIR>/sources.xml`

What's your suggestions?

**Comment by JohanLorenzo** [comment]
wget behaves the same way as option 2 by default. So I think it's fine to do the same.
